---
- name: Add Users
  hosts: basics-host
  gather_facts: false

  tasks:
  - name: Add users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop: 
      - user1
      - user2
      - user3
