---
- name: Write file on localhost
  hosts: basics-host
  gather_facts: false
  vars:
    fav_foods: 
      - tacos
      - burgers
      - donuts

  tasks:
  - name: Write file test.txt to the temp folder
    ansible.builtin.template:
      dest: /tmp/food.txt
      src: food.txt.j2
      
  - name: Grab contents of file
    ansible.builtin.shell: cat /tmp/food.txt
    register: file_contents

  - name: Display file_contents 
    ansible.builtin.debug:
      var: file_contents.stdout_lines
