---
- name: Conditional
  hosts: basics-host
  #gather_facts: false
  tasks:
  - name: Write file test.txt to the temp folder
    when: ansible_facts.distribution == "Rocky"
    ansible.builtin.debug:
      var: ansible_facts.distribution
